site: georgi dimitrov
url: #yoururl
title: georgi dimitrov
description: ""
twitter:
  username: nonsofia
  card: summary
  
host: 0.0.0.0

permalink: pretty

baseurl: "/larypsed"

# highlighter: none

exclude:
  - .jekyll-cache
  
# compress_html:
  # clippings: all
  # comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

# plugins:
#   - jekyll-paginate
#   - jekyll-seo-tag
#   - jekyll-sitemap  

collections:
  pages:
    output: true
    permalink: /:name
  
